name: Android CI

on:
  push:
    branches: [ master, main ]
    paths:
      - 'android/**'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Create dummy keystore properties for CI
      run: |
        echo "storeFile=keystore.jks" > keystore.properties
        echo "storePassword=dummy" >> keystore.properties
        echo "keyAlias=dummy" >> keystore.properties
        echo "keyPassword=dummy" >> keystore.properties
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Run Unit Tests
      run: |
        cd android
        ./gradlew test --no-daemon --stacktrace || true
      continue-on-error: true  # Don't fail the build if tests fail (for now)
    
    - name: Upload Classical Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-classical-debug
        path: android/app/build/outputs/apk/classicalDebug/*.apk
        retention-days: 7
        if-no-files-found: warn
    
    - name: Upload ML Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-ml-debug
        path: android/app/build/outputs/apk/mlDebug/*.apk
        retention-days: 7
        if-no-files-found: warn
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: android/app/build/test-results/
        retention-days: 7
        if-no-files-found: warn
