name: Android CI

on:
  push:
    branches: [ master, main ]
    paths:
      - 'android/**'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon
      
    - name: Run Unit Tests
      run: |
        cd android
        ./gradlew test --no-daemon
      continue-on-error: true  # Don't fail the build if tests fail (for now)
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 7
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: android/app/build/test-results/
        retention-days: 7