name: Sync Documentation

on:
  push:
    branches: [ master, main ]
    paths:
      - 'README.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Sync documentation files
      id: sync
      shell: bash
      run: |
        echo "Syncing documentation files..."
        
        # Create android directory if it doesn't exist
        mkdir -p android
        
        # Track if changes were made
        CHANGED=false
        
        # Check if README.md exists in root and sync to android
        if [ -f "README.md" ]; then
          if [ ! -f "android/README.md" ] || ! diff -q README.md android/README.md > /dev/null 2>&1; then
            echo "Copying README.md to android/"
            cp README.md android/README.md
            CHANGED=true
          fi
        fi
        
        # Check if CHANGELOG.md exists in root and sync to android
        if [ -f "CHANGELOG.md" ]; then
          if [ ! -f "android/CHANGELOG.md" ] || ! diff -q CHANGELOG.md android/CHANGELOG.md > /dev/null 2>&1; then
            echo "Copying CHANGELOG.md to android/"
            cp CHANGELOG.md android/CHANGELOG.md
            CHANGED=true
          fi
        fi
        
        if [ "$CHANGED" = true ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Documentation files synced successfully"
        else
          echo "No changes needed"
        fi
    
    - name: Commit and push if changed
      if: steps.sync.outputs.changed == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add android/README.md android/CHANGELOG.md
        git diff --staged --quiet || (
          git commit -m "docs: Auto-sync documentation to android directory [skip ci]"
          git push
        )
